#pragma once
#include <credentialprovider.h>

// The indexes of each of the fields in our credential provider's appended tiles.
enum FIELD_ID
{
	FID_LOGO = 0,
	FID_LARGE_TEXT = 1,
	FID_SMALL_TEXT = 2,
	FID_USERNAME = 3,
	FID_PASSWORD = 4,
	FID_OTP = 5,
	FID_FIDO_PIN = 6,
	FID_NEW_PASS_1 = 7,
	FID_NEW_PASS_2 = 8,
	FID_SUBMIT_BUTTON = 9,
	FID_SUBTEXT = 10,
	FID_OFFLINE_INFO = 11,
	FID_FIDO_ONLINE = 12, // Passkey in first step, WebAuthn in second if triggered
	FID_FIDO_OFFLINE = 13, // Shown if offline FIDO2 is available (both Passkey/WebAuthn)
	FID_RESET_LINK = 14,
	FID_CANCEL_ENROLLMENT = 15, // PI v3.12+
	FID_NUM_FIELDS = 16
};

// The first value indicates when the tile is displayed (selected, not selected)
// the second indicates things like whether the field is enabled, whether it has key focus, etc.
struct FIELD_STATE_PAIR
{
	CREDENTIAL_PROVIDER_FIELD_STATE cpfs;
	CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE cpfis;
};

// These two arrays are seperate because a credential provider might
// want to set up a credential with various combinations of field state pairs 
// and field descriptors.

// The field state value indicates whether the field is displayed
// in the selected tile, the deselected tile, or both.
// The Field interactive state indicates when 

// USERNAME
static const FIELD_STATE_PAIR s_rgScenarioUsername[] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LOGO
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LARGE_TEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SMALL_TEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_FOCUSED },		// FID_USERNAME
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_PASSWORD
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_OTP
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_WAN_PIN
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBMIT_BUTTON
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBTEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_OFFLINE_INFO
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_ONLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_OFFLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_RESET_LINK
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_CANCEL_ENROLLMENT
};

// USERNAMEPASSWORD
static const FIELD_STATE_PAIR s_rgScenarioUsernamePassword[] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LOGO
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LARGE_TEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SMALL_TEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_FOCUSED },		// FID_USERNAME
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_PASSWORD
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_OTP
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_WAN_PIN
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBMIT_BUTTON
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBTEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_OFFLINE_INFO
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_ONLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_OFFLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_RESET_LINK
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_CANCEL_ENROLLMENT
};

// PRIVACYIDEA
static const FIELD_STATE_PAIR s_rgScenarioPrivacyIDEA[] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LOGO
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LARGE_TEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SMALL_TEXT
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_USERNAME
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_PASSWORD
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_FOCUSED },		// FID_OTP
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_WAN_PIN
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBMIT_BUTTON
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBTEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_OFFLINE_INFO
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_ONLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_OFFLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_RESET_LINK
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_CANCEL_ENROLLMENT
};

// PASSWORD
static const FIELD_STATE_PAIR s_rgScenarioPassword[] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LOGO
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LARGE_TEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SMALL_TEXT
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_USERNAME
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_FOCUSED },		// FID_PASSWORD
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_OTP
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_WAN_PIN
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBMIT_BUTTON
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBTEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_OFFLINE_INFO
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_ONLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_OFFLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_RESET_LINK
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_CANCEL_ENROLLMENT
};

// CHANGE PASSWORD
static const FIELD_STATE_PAIR s_rgScenarioPasswordChange[] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LOGO
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LARGE_TEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SMALL_TEXT
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_USERNAME
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_PASSWORD
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_OTP
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_WAN_PIN
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_FOCUSED },		// FID_NEW_PASS_1
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_NEW_PASS_1
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBMIT_BUTTON
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBTEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_OFFLINE_INFO
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_ONLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_OFFLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_RESET_LINK
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_CANCEL_ENROLLMENT
};

static const FIELD_STATE_PAIR s_rgScenarioUnlockFirstStepPassword[] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LOGO
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LARGE_TEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SMALL_TEXT
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_USERNAME
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_FOCUSED },		// FID_PASSWORD
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_OTP
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_WAN_PIN
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBMIT_BUTTON
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBTEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_OFFLINE_INFO
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_ONLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_OFFLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_RESET_LINK
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_CANCEL_ENROLLMENT
};

// Show only FID_PASSWORD to get the PIN of the Device
static const FIELD_STATE_PAIR s_rgScenarioSecurityKey[] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LOGO
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },					// FID_LARGE_TEXT
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SMALL_TEXT
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_USERNAME
	{ CPFS_HIDDEN, CPFIS_FOCUSED },							// FID_PASSWORD
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_OTP
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_WAN_PIN
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_NEW_PASS_1
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_SUBMIT_BUTTON
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_SUBTEXT
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_OFFLINE_INFO
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },			// FID_FIDO2_ONLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_FIDO2_OFFLINE
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_RESET_LINK
	{ CPFS_HIDDEN, CPFIS_NONE },							// FID_CANCEL_ENROLLMENT
};

// Field descriptors for unlock and logon.
// The first field is the index of the field.
// The second is the type of the field.
// The third is the name of the field, NOT the value which will appear in the field.
static CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR s_rgScenarioCredProvFieldDescriptors[] =
{
	{ FID_LOGO, CPFT_TILE_IMAGE, L"" },
	{ FID_LARGE_TEXT, CPFT_LARGE_TEXT, L"LargeText" },
	{ FID_SMALL_TEXT, CPFT_SMALL_TEXT, L"SmallText" },
	{ FID_USERNAME, CPFT_EDIT_TEXT, L"Username" },
	{ FID_PASSWORD, CPFT_PASSWORD_TEXT, L"Password" },
	{ FID_OTP, CPFT_PASSWORD_TEXT, L"One-Time Password" },
	{ FID_FIDO_PIN, CPFT_PASSWORD_TEXT, L"Security Key PIN" },
	{ FID_NEW_PASS_1, CPFT_PASSWORD_TEXT, L"New Password" },
	{ FID_NEW_PASS_2, CPFT_PASSWORD_TEXT, L"Confirm password" },
	{ FID_SUBMIT_BUTTON, CPFT_SUBMIT_BUTTON, L"Submit" },
	{ FID_SUBTEXT, CPFT_SMALL_TEXT, L"Sign in to: "},
	{ FID_OFFLINE_INFO, CPFT_SMALL_TEXT, L"Available offline token: "},
	{ FID_FIDO_ONLINE, CPFT_COMMAND_LINK, L"Use Security Key Online"},
	{ FID_FIDO_OFFLINE, CPFT_COMMAND_LINK, L"Use Security Key Offline"},
	{ FID_RESET_LINK, CPFT_COMMAND_LINK, L"Reset Login"},
	{ FID_CANCEL_ENROLLMENT, CPFT_COMMAND_LINK, L"Not now"},
};